### ISSUE TITLE
I installed the tool but I keep getting a folder and not an excutable file

### ISSUE THREAD

**Issue by abdalmajid77** [AGDDoS/AGDDoS#16]
I install the zip file on my linux vm and i got a zip file which i exracted and got a folder

**Comment by xiaozhu2007** [comment]
Please provide more things, such as screenshots?

**Comment by xiaozhu2007** [comment]
> I install the zip file on my linux vm and i got a zip file which i exracted and got a folder

Why not try Windows excutable file? <https://github.com/AGDDoS/AGDDoS/suites/6798322628/artifacts/261009682>
